// Import Google fonts using next/font
import { Geist, Geist_Mono } from "next/font/google";
// Import global CSS styles
import "./globals.css";
// (Unused import) import { link } from "fs";

// Load Geist Sans font and assign to CSS variable
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Load Geist Mono font and assign to CSS variable
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the application (used by Next.js for SEO and icons)
export const metadata = {
  title: "Crud",
  description: "Generated by create next app",
  icons: {
    icon: "perypherics.png",
  },
};

// RootLayout wraps all pages and applies global styles and fonts
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}